- name: Отключить IPv6 на всех интерфейсах
  become: yes
  lineinfile:
    path: "{{ sysctl_config_path }}"
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
    create: yes
    state: present

- name: Отключить IPv6 на локальных интерфейсах
  become: yes
  lineinfile:
    path: "{{ sysctl_config_path }}"
    line: 'net.ipv6.conf.default.disable_ipv6 = 1'
    create: yes
    state: present

- name: Применить настройки ядра без перезагрузки
  become: yes
  command: sysctl -p
