prometheus_version: "2.52.0"
prometheus_arch: "linux-amd64"
prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
prometheus_install_dir: "/opt/prometheus"
prometheus_directory: "{{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}"
prometheus_data_dir: "/var/lib/prometheus"
web_prometheus_template: "web.yml.j2"
prometheus_template: "prometheus.yml.j2"
prometheus_service_template: "prometheus.service.j2"
prometheus_key: "{{ prometheus_config_dir }}/prometheus.key"
prometheus_cert: "{{ prometheus_config_dir }}/prometheus.crt"
