---
- name: Обновление пакетов
  apt:
    update_cache: yes

- name: Установка необходимых пакетов для SSH
  apt:
    name: openssh-server
    state: latest

- name: Очистка файла known_hosts
  known_hosts:
    path: "{{ ssh_known_hosts_path }}"
    name: "{{ hostvars[item].ansible_host }}"
    state: absent
  loop: "{{ groups['all'] }}"

- name: Генерация SSH ключей для каждой машины
  openssh_keypair:
    path:  "{{ ssh_key_path }}"
    type: rsa
    size: "{{ rsa_key_size }}"
    comment: "{{ inventory_hostname }}"
    force: no
  register: ssh_key_gen

- name: Сбор публичных ключей всех машин
  fetch:
    src: "{{ ssh_key_path }}.pub"
    dest: "{{ public_keys_path }}"
    flat: yes

- name: Добавление отпечатков ключей хостов в known_hosts
  known_hosts:
    path: "{{ ssh_known_hosts_path }}"
    name: "{{ hostvars[item].ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + hostvars[item].ansible_host) }}"
    state: present
  loop: "{{ groups['all'] }}"

- name: Распределение публичных ключей на все машины
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "pub_keys/*.pub"

- name: Установка правильных прав доступа для SSH ключей
  file:
    path: "{{ ssh_key_path }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0600'

- name: Настройка файла конфигурации SSH для всех узлов
  ansible.builtin.template:
    src: "{{ ssh_config_template }}"
    dest: "{{ ssh_user_config }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0644'

- name: Настройка файла конфигурации SSH для root
  ansible.builtin.template:
    src: "{{ root_ssh_config_template }}"
    dest: "{{ root_ssh_config }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
