# URL для скачивания
grafana_download_url: "https://dl.grafana.com/oss/release/grafana_8.5.0_amd64.deb"

# Директории
grafana_config: "/etc/grafana"

# Файлы безопасности
prometheus_key: "{{ path_settings.prometheus_config_dir }}/prometheus.key"
prometheus_cert: "{{ path_settings.prometheus_config_dir }}/prometheus.crt"

# Шаблоны
grafana_service_template: "grafana_server.service.j2"

# Пользователи
grafana_user: admin
grafana_password: admin
