- name: Разрешение исходящего трафика SMTP
  ansible.builtin.iptables:
    table: filter
    chain: OUTPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop: "{{ mail_ports.smtp }}"

- name: Разрешение входящего трафика IMAP и POP3
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate:
      - NEW
      - ESTABLISHED
    jump: ACCEPT
  loop: "{{ mail_ports.imap + mail_ports.pop3 }}"
