---
- name: Установка пакета VPN на сервер VPN
  hosts: vpn
  become: yes
  tasks:
    - name: Отключение unattended-upgrades перед выполнением основных задач
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: stopped
      become: true

    - name: Обновление списка пакетов
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Установка пакета VPN
      apt:
        name: vpn
        state: present
        update_cache: yes
        allow_unauthenticated: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Включение unattended-upgrades после выполнения основных задач
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: started
      become: true
