---
- name: Установка пакета vpn на сервер VPN
  hosts: VPN
  become: yes
  tasks:
    - name: Обновление списка пакетов
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Установка пакета VPN
      shell: apt-get install -y vpn
