- hosts: all
  become: true
  gather_facts: true
  roles:
    - disable_unattended_upgrades
    - ssh
    - timezone
    - disable_ipv6
    - firewall
    - custom_repo

- hosts: ca
  become: true
  gather_facts: true
  roles:
    - { role: package_install, package_name: ca }

- hosts: vpn
  become: true
  gather_facts: true
  roles:
    - vpn_firewall
    - msmtp
    - vpn_configurator
    - { role: package_install, package_name: vpn }
    - openvpn_exporter

- hosts: all
  become: true
  gather_facts: true
  roles:
    - node_exporter

#- hosts: monitoring
#  become: true
#  gather_facts: true
#  roles:
#    - prometheus
