- hosts: all
  become: true
  gather_facts: true
  roles:
    - ssh
    - timezone
    - disable_ipv6
    - firewall
    - custom_repo

- hosts: ca
  become: true
  gather_facts: true
  roles:
    - role: package_install
      vars:
        package_name: ca
    - role: node_exporter

- hosts: vpn
  become: true
  gather_facts: true
  roles:
    - vpn_firewall
    - msmtp
    - vpn_configurator
    - role: package_install
      vars:
        package_name: vpn
    - role: node_exporter

- hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - prometheus
