---
- name: Настройка SMTP на серверах VPN и мониторинга
  hosts: vpn:monitoring
  become: true
  tasks:
    - name: Установка пакета msmtp
      apt:
        name: msmtp
        state: present

    - name: Создание файла конфигурации msmtprc
      copy:
        content: |
          defaults
          auth           on
          tls            on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt

          # Яндекс SMTP сервер
          account        yandex
          host           smtp.yandex.ru
          port           587
          from           {{ yandex_email }}
          user           {{ yandex_email }}
          password       {{ yandex_email_password }}

          # Установка аккаунта по умолчанию
          account default : yandex
        dest: ~/.msmtprc
        mode: "0600"

    - name: Проверка отправки тестового письма
      shell: echo "Привет, это тестовое письмо от msmtp." | msmtp {{ yandex_email }}
      register: send_email_result
      ignore_errors: true

    - name: Вывод результата отправки письма
      debug:
        var: send_email_result.stdout
