---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Установка пакета iptables-persistent
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Настройка базовых правил iptables на всех серверах
      ansible.builtin.shell: |
        # Очистка текущих правил
        iptables -F
        iptables -t nat -F
        iptables -t mangle -F
        iptables -X

        # Установка политик по умолчанию
        iptables -P INPUT DROP
        iptables -P FORWARD DROP
        iptables -P OUTPUT ACCEPT

        # Разрешение локального трафика и установленных соединений
        iptables -A INPUT -i lo -j ACCEPT
        iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

        # Разрешение SSH доступа для текущего хоста
        iptables -A INPUT -p tcp --dport 22 -s {{ local_host_ip }} -j ACCEPT

        # Разрешение SSH доступа для всех хостов в инвентаре
        {% for host in groups['all'] %}
        iptables -A INPUT -p tcp --dport 22 -s {{ hostvars[host]['ansible_host'] }} -j ACCEPT
        {% endfor %}

    - name: Находим основной сетевой интерфейс VPN сервера
      set_fact:
        main_interface: "{{ ansible_default_ipv4.interface }}"
      when: ansible_default_ipv4.interface is defined and 'VPN' in group_names

    - name: Настройка правил iptables для VPN сервера
      ansible.builtin.shell: |
        # Разрешение трафика для VPN
        iptables -A INPUT -i {{ main_interface }} -m state --state NEW -p udp --dport 1194 -j ACCEPT
        iptables -A INPUT -i tun+ -j ACCEPT
        iptables -A FORWARD -i tun+ -j ACCEPT
        iptables -A FORWARD -i tun+ -o {{ main_interface }} -m state --state RELATED,ESTABLISHED -j ACCEPT
        iptables -A FORWARD -i {{ main_interface }} -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
        
        # Настройка NAT для клиентов VPN
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o {{ main_interface }} -j MASQUERADE
      when: "'VPN' in group_names"

    - name: Сохранение настроек iptables
      ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4

    - name: Убедиться, что правила iptables будут сохранены после перезагрузки
      ansible.builtin.shell: dpkg-reconfigure -f noninteractive iptables-persistent

    - name: Вывод сообщения об успешном выполнении
      ansible.builtin.debug:
        msg: "Новые правила iptables применены и сохранены."
