---
- name: Настройка пользовательского APT репозитория на всех машинах
  hosts: all
  become: yes
  tasks:
    - name: Загрузка и добавление GPG-ключа репозитория
      become: yes
      shell: |
        curl -sL https://raw.githubusercontent.com/arinazaikina/azaikina-deb-repo/main/repo-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/azaikina-deb-repo.gpg >/dev/null

    - name: Добавление APT репозитория вручную
      become: yes
      shell: |
        echo 'deb [signed-by=/usr/share/keyrings/azaikina-deb-repo.gpg] https://arinazaikina.github.io/azaikina-deb-repo/ /' | sudo tee /etc/apt/sources.list.d/arinazaikina-deb-repo.list
      args:
        creates: /etc/apt/sources.list.d/arinazaikina-deb-repo.list

    - name: Отключение переводов APT
      copy:
        dest: /etc/apt/apt.conf.d/99disable-translations
        content: Acquire::Languages "none";

    - name: Обновление списка пакетов
      apt:
        update_cache: yes
        cache_valid_time: 3600
