{
 "title": "Инфраструктура VPN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Доступное дисковое пространство",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs\"} * 100"
    }
   ]
  },
  {
   "title": "Доступная оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Средняя нагрузка за 1 минуту",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Активность процессора",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Node Exporter CA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-ca\"}"
    }
   ]
  },
  {
   "title": "Node Exporter VPN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-vpn\"}"
    }
   ]
  },
  {
   "title": "Node Exporter Monitoring",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-monitoring\"}"
    }
   ]
  },
  {
   "title": "Node Exporter Backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-backup\"}"
    }
   ]
  },
  {
   "title": "OpenVPN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openvpn_build_info" }
   ]
  }
 ]
}