#!/bin/sh

set -e

case "$1" in
    configure)
        /usr/bin/init_pki.sh
        /usr/bin/setup_vpn_server.sh
        /usr/bin/setup_client_config.sh
        chmod 700 /usr/bin/make_config.sh
        ln -sf /usr/bin/make_config.sh /usr/bin/make_config
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        if [ "$1" = "purge" ]; then
            rm -f /usr/bin/make_config
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
