#!/bin/sh

set -e

case "$1" in
    configure)
        /usr/bin/init_pki.sh
        /usr/bin/setup_vpn_server.sh
        /usr/bin/setup_client_config.sh
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
