#!/bin/bash

set -e

case "$1" in
    remove|purge)
        # Останавливаем сервис
        if [ -x "/bin/systemctl" ]; then
            echo "Остановка OpenVPN сервиса..."
            /bin/systemctl stop openvpn-server@server.service > /dev/null 2>&1 || true
        fi
         rm -f /usr/bin/make_config

        # При полном удалении (purge) удаляем конфигурационные файлы и логи
        if [ "$1" = "purge" ]; then
            echo "Удаление конфигурационных файлов..."
            rm -rf /etc/openvpn/server/
            rm -rf /etc/openvpn/client/
            echo "Очистка логов..."
            find /var/log/openvpn/ -type f -delete
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Здесь ничего не делаем
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
