- name: Создание системной группы prometheus
  group:
    name: prometheus
    system: yes
  become: true

- name: Создание системного пользователя prometheus
  user:
    name: prometheus
    group: prometheus
    home: /usr/share/prometheus
    system: yes
    createhome: no
    shell: /bin/false
  become: true

- name: Скачивание архива Prometheus
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"

- name: Скачивание архива AlertManager
  get_url:
    url: "{{ alert_manager_download_url }}"
    dest: "/tmp/prometheus-{{ alert_manager_version }}.{{ alert_manager_arch }}.tar.gz"

- name: Создание целевой директории для Prometheus
  file:
    path: "{{ prometheus_install_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Создание целевой директории для AlertManager
  file:
    path: "{{ alert_manager_install_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Распаковка архива Prometheus
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
    dest: "{{ prometheus_install_dir }}"
    creates: "{{ prometheus_directory }}"
    remote_src: yes
  become: yes

- name: Распаковка архива AlertManager
  unarchive:
    src: "/tmp/prometheus-{{ alert_manager_version }}.{{ alert_manager_arch }}.tar.gz"
    dest: "{{ alert_manager_install_dir }}"
    creates: "{{ alert_manager_directory }}"
    remote_src: yes
  become: yes

- name: Создание символических ссылок на исполняемые файлы Prometheus
  file:
    src: "{{ prometheus_directory }}/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  loop:
    - { src: 'prometheus', dest: 'prometheus' }
    - { src: 'promtool', dest: 'promtool' }

- name: Создание директорий для конфигураций Prometheus
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
    mode: '0755'
  loop:
    - "{{ path_settings.prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"
    - "{{ path_settings.prometheus_config_dir }}/consoles"
    - "{{ path_settings.prometheus_config_dir }}/console_libraries"

- name: Копирование конфигурационных файлов и библиотек интерфейса
  copy:
    src: "{{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  loop:
    - { src: "consoles", dest: "{{ path_settings.prometheus_config_dir }}/consoles" }
    - { src: "console_libraries", dest: "{{ path_settings.prometheus_config_dir }}/console_libraries" }

- name: Копирование amtool и alertmanager в /usr/bin
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: true
  loop:
    - { src: "{{ alert_manager_directory }}/amtool", dest: "/usr/bin/amtool" }
    - { src: "{{ alert_manager_directory }}/alertmanager", dest: "/usr/bin/alertmanager" }
  become: yes

- name: Создание символических ссылок для AlertManager
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "/usr/bin/amtool", dest: "/usr/local/bin/amtool" }
    - { src: "/usr/bin/alertmanager", dest: "/usr/local/bin/alertmanager" }
  become: yes

- name: Создание директории для хранения данных AlertManager
  file:
    path: "{{ path_settings.prometheus_config_dir }}/alertmanager_data"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: yes

- name: Создание файла конфигурации AlertManager
  template:
    src: "{{ alert_manager_template }}"
    dest: "{{ path_settings.prometheus_config_dir }}/alertmanager.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: true

- name: Генерация ключа и CSR для сервера Prometheus
  command: "./easyrsa --batch --subject-alt-name=IP:{{ hostvars[inventory_hostname]['ansible_host'] }} gen-req prometheus nopass"
  args:
    chdir: "{{ ca.easy_rsa_dir }}"
  delegate_to: ca_server
  become: true
  become_user: "{{ ansible_ssh_user }}"
  run_once: true

- name: Подписание сертификата для сервера Prometheus
  command: "./easyrsa --batch sign-req server prometheus"
  args:
    chdir: "{{ ca.easy_rsa_dir }}"
  delegate_to: ca_server
  become: true
  become_user: "{{ ansible_ssh_user }}"
  run_once: true

- name: Извлечение сертификата и ключа Prometheus на управляющий узел
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    flat: yes
  loop:
    - { src: "{{ ca.prometheus.cert }}", dest: "/tmp/prometheus.crt" }
    - { src: "{{ ca.prometheus.key }}", dest: "/tmp/prometheus.key" }
  delegate_to: ca_server

- name: Копирование сертификата и ключа Prometheus на целевую машину
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "/tmp/prometheus.crt", dest: "{{ prometheus_cert }}" }
    - { src: "/tmp/prometheus.key", dest: "{{ prometheus_key }}" }

- name: Удаление временных файлов с управляющего узла
  local_action:
    module: file
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - "prometheus.crt"
    - "prometheus.key"
  become: false

- name: Извлечение сертификатов node экспортеров с удостоверяющего центра на управляющий узел
  fetch:
    src: "{{ ca.cert_dir }}/{{ item }}_node_exporter.crt"
    dest: "/tmp/{{ item }}_node_exporter.crt"
    flat: yes
  loop: "{{ groups['all'] }}"
  delegate_to: ca_server

- name: Копирование сертификатов node экспортеров
  copy:
    src: "/tmp/{{ item }}_node_exporter.crt"
    dest: "{{ path_settings.prometheus_config_dir }}/{{ item }}_node_exporter.crt"
  loop: "{{ groups['all'] }}"

- name: Удаление сертификатов node экспортеров с управляющего узла
  local_action:
    module: file
    path: "/tmp/{{ item }}_node_exporter.crt"
    state: absent
  loop: "{{ groups['all'] }}"
  become: false

- name: Настройка прав на файлы
  file:
    path: "{{ item.path }}"
    owner: prometheus
    group: prometheus
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ prometheus_cert }}", mode: '0640' }
    - { path: "{{ prometheus_key }}", mode: '0640' }
    - { path: "/usr/local/bin/prometheus", mode: '0755' }
    - { path: "/usr/local/bin/promtool", mode: '0755' }
  become: true

- name: Настройка прав на сертификаты node экспортеров
  file:
    path: "{{ path_settings.prometheus_config_dir }}/{{ item }}_node_exporter.crt"
    owner: prometheus
    group: prometheus
    mode: '0644'
  loop: "{{ groups['all'] }}"

- name: Установка Apache2-Utils
  apt:
    name: apache2-utils
    state: present
  become: true

- name: Генерация хэша пароля для базовой аутентификации
  command: htpasswd -nbB {{ ansible_ssh_user }} "{{ monitoring_password }}"
  register: password_hash
  changed_when: false
  become: true

- name: Извлечение хэша пароля
  set_fact:
    user_password_hash: "{{ password_hash.stdout.split(':')[1] }}"

- name: Создание файла web.yml для Prometheus
  template:
    src: "{{ prometheus_web_template }}"
    dest: "{{ path_settings.prometheus_config_dir }}/web.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: true

- name: Создание файла правил AlertManager
  template:
    src: "{{ alert_rules_template }}"
    dest: "{{ path_settings.prometheus_config_dir }}/rules.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: true

- name: Создание файла конфигурации Prometheus
  template:
    src: "{{ prometheus_template }}"
    dest: "{{ path_settings.prometheus_config_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: true

- name: Копирование systemd unit файла для Prometheus
  template:
    src: "{{ prometheus_service_template }}"
    dest: /etc/systemd/system/prometheus.service
  notify:
    - reload systemd
    - restart prometheus
  become: true

- name: Копирование systemd unit файла для AlertManager
  template:
    src: "{{ alert_manager_service_template }}"
    dest: /etc/systemd/system/prometheus_alertmanager.service
  notify:
    - reload systemd
    - restart prometheus_alertmanager
  become: true

- name: Включение и запуск сервиса AlertManager
  systemd:
    name: prometheus_alertmanager
    enabled: true
    state: started
  become: true

- name: Включение и запуск сервиса Prometheus
  systemd:
    name: prometheus
    enabled: true
    state: started
  become: true

- name: Разрешение доступа управляющему узлу к Prometheus
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ local_host_ip }}"
    destination_port: "{{ network_ports.prometheus }}"
    jump: ACCEPT

- name: Разрешение доступа к AlertManager для управляющего узла и узла мониторинга
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ item }}"
    destination_port: "{{ network_ports.alert_manager }}"
    jump: ACCEPT
  loop:
    - "{{ local_host_ip }}"
    - "{{ hostvars['monitoring_server']['ansible_host'] }}"
  become: true

- name: Сохранение настроек iptables
  include_tasks: ../includes/iptables_save.yml
