#!/bin/bash

. /usr/share/debconf/confmodule

# Функция для валидации IP-адреса
validate_ip() {
    if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        IFS='.' read -r -a ip <<< "$1"
        if [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]; then
            return 0
        fi
    fi
    return 1
}

# Функция для валидации списка IP-адресов
validate_ips() {
    # shellcheck disable=SC2206
    local ips=(${1//,/ })
    for ip in "${ips[@]}"; do
        if ! validate_ip "$ip"; then
            return 1
        fi
    done
    return 0
}

# Запрос IP-адреса локальной машины
db_input high ca/ip1 || true
db_go
db_get ca/ip1
until validate_ip "$RET"; do
    echo "Введён некорректный IP-адрес. Пожалуйста, попробуйте еще раз."
    db_input critical ca/ip1 || true
    db_go
    db_get ca/ip1
done

# Запрос списка IP-адресов VPN-серверов
db_input high ca/ip_list || true
db_go
db_get ca/ip_list
until validate_ips "$RET"; do
    echo "Введён некорректный список IP-адресов. Пожалуйста, попробуйте еще раз."
    db_input critical ca/ip_list || true
    db_go
    db_get ca/ip_list
done

db_stop
