#!/bin/sh

set -e

case "$1" in
    configure)
        if [ -n "$SUDO_USER" ]; then
            HOME_USER=$(getent passwd "$SUDO_USER" | cut -d: -f6)
        else
            HOME_USER="$HOME"
        fi

        /usr/bin/setup_easyrsa_ca.sh
        chown -R "$SUDO_USER":"$SUDO_USER" "$HOME_USER/easy-rsa"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
