#!/bin/bash

set -e

if [ -n "$SUDO_USER" ]; then
    HOME_USER=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    HOME_USER="$HOME"
fi

case "$1" in
    remove|purge)
        if [ "$1" = "purge" ]; then
            echo "Очищение всех данных, связанных с пакетом"
            rm -rf "$HOME_USER/easy-rsa"
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
