#!/bin/bash

set -e

case "$1" in
    remove|purge)

        if [ "$1" = "purge" ]; then
            # Команды для выполнения при полном удалении пакета (purge)
            echo "Очищение всех данных, связанных с пакетом"
            rm -rf /root/easy-rsa
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
