name: Сборка и развертывание пакетов

on:
  push:
    branches:
      - main
    paths:
      - 'ca/**'
      - 'vpn/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Установка зависимостей для сборки DEB пакета
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev debhelper devscripts

      - name: Настройка конфигурации Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Определение изменённых директорий
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Измененные файлы: $CHANGED_FILES"
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep -E 'ca/|vpn/' | awk -F'/' '{print $1}' | uniq | tr '\n' ' ')
          echo "CHANGED_DIRS=$CHANGED_DIRS" >> $GITHUB_ENV
          echo "Измененные директории: $CHANGED_DIRS"

      - name: Инкрементирование версии и обновление changelog
        env:
          DEBEMAIL: "actions@github.com"
          DEBFULLNAME: "GitHub Actions"
          EMAIL: "actions@github.com"
        if: env.CHANGED_DIRS != ''
        run: |
          for DIR in $CHANGED_DIRS; do
            cd $DIR
            CURRENT_VERSION=$(dpkg-parsechangelog --show-field Version)
            BASE_VERSION=$(echo $CURRENT_VERSION | cut -d'-' -f1)
            REVISION=$(echo $CURRENT_VERSION | cut -d'-' -f2)
            NEW_REVISION=$(($REVISION + 1))
            NEW_VERSION="${BASE_VERSION}-${NEW_REVISION}"
            dch --newversion $NEW_VERSION "Automated increment based on new commit."
            dch -r ""
            cat debian/changelog
            git add debian/changelog
            git commit -m "Update $DIR changelog to version $NEW_VERSION"
            git push
            dpkg-buildpackage -us -uc -b
            cd ..
            echo "Список .deb файлов в $GITHUB_WORKSPACE"
            ls $GITHUB_WORKSPACE/*.deb
          done

      - name: Клонирование репозитория DEB пакетов
        uses: actions/checkout@v2
        with:
          repository: 'arinazaikina/azaikina-deb-repo'
          token: ${{ secrets.DEB_REPO_ACCESS_TOKEN }}
          path: 'deb-repo'

      - name: Копирование DEB пакета в репозиторий
        run: |
          shopt -s nullglob
          files=($GITHUB_WORKSPACE/*.deb)
          if [ ${#files[@]} -gt 0 ]; then
            cp $GITHUB_WORKSPACE/*.deb ./deb-repo/
          else
            echo "Файлы .deb не найдены."
            exit 1
          fi

      - name: Настройка конфигурации Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Фиксация изменений и публикация в репозиторий
        run: |
          cd deb-repo
          git add .
          git commit -m "Update DEB packages to version $NEW_VERSION."
          git push --set-upstream origin main
